<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="TU NOMBRE, AQUÍ" />


<title>Evaluación curso R</title>

<script src="entrega_files/header-attrs-2.20/header-attrs.js"></script>
<script src="entrega_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="entrega_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="entrega_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="entrega_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="entrega_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="entrega_files/navigation-1.1/tabsets.js"></script>
<link href="entrega_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="entrega_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div id="header">



<h1 class="title toc-ignore">Evaluación curso R</h1>
<h4 class="author">TU NOMBRE, AQUÍ</h4>

</div>


<div id="entrega" class="section level2">
<h2>Entrega</h2>
<ul>
<li>Recuerda completar tu <strong>nombre en el apartado
author</strong>.</li>
<li>Además del código, no olvides completar las respuestas a las
preguntas indicadas en negrita.</li>
<li>Si tienes dudas/dificultades, <strong>puedes contactar con los
profesores</strong>.</li>
<li>Deadline: <strong>viernes 16 de junio, 23:59</strong>.</li>
<li>Puedes realizar la entrega en el mail: <strong><a
href="mailto:constantino.garciama@ceu.es"
class="email">constantino.garciama@ceu.es</a></strong>.</li>
<li>La entrega consistirá en el fichero que se genera al hacer
<code>Knit</code> (un fichero <code>html</code> o
<code>pdf</code>).</li>
</ul>
</div>
<div id="apuestas-de-adolescentes-en-uk" class="section level2">
<h2>Apuestas de adolescentes en UK</h2>
<p>El conjunto de datos <code>teengamb.csv</code> contiene datos sobre
las tasas de juego entre los adolescentes en Gran Bretaña, su género y
estatus socioeconómico. Una pregunta que nos puede interesar es
<strong>si los ingresos del adolescente y su sexo influyen en la
cantidad de dinero apostado (céntrate solo en las variables
<code>income</code>, <code>sex</code> y <code>gamble</code>)</strong> …
Sigue los siguientes pasos para crear un ANCOVA…</p>
<div id="a-carga-los-datos" class="section level3">
<h3>1a) Carga los datos…</h3>
<pre class="r"><code># Carga los datos
teengamb &lt;- read.csv(&quot;teengamb.csv&quot;)</code></pre>
</div>
<div id="b-visualiza-los-datos" class="section level3">
<h3>1b) Visualiza los datos…</h3>
<p>…para valorar si el modelo debe incluir interacciones. Para ello,
escribe el código que genera una gráfica similar a la siguiente:</p>
<p><img src="expected-plot.png" /></p>
<pre class="r"><code>library(&quot;tidyverse&quot;)  # carga ggplot</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.0     ✔ readr     2.1.4
## ✔ forcats   1.0.0     ✔ stringr   1.5.0
## ✔ ggplot2   3.4.1     ✔ tibble    3.2.0
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ✔ purrr     1.0.1     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors</code></pre>
<pre class="r"><code># completa el siguiente código
ggplot(teengamb, aes(x = income, col=sex, y=gamble)) + 
  geom_point() + # añade la geometría adecuada para los puntos
  geom_smooth(method = &quot;lm&quot;, se = FALSE)  # añade las rectas de regresión</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="entrega_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>La gráfica anterior apoya que hay interacciones entre las variables
<code>sex</code> e <code>income</code>. <strong>Explica los motivos
brevemente</strong> (Pista: ¿son las rectas paralelas?)</p>
</div>
<div id="crea-el-modelo" class="section level3">
<h3>2) Crea el modelo…</h3>
<p>… y obtén los intervalos de confianza para los coeficientes y su
significación.</p>
<pre class="r"><code># Crea un modelo con interacciones en base a tu conclusión del apartado anterior
gamb_model &lt;- lm(gamble ~ sex * income, data = teengamb)

# Obtén p-valores e intervalos de confianza
summary(gamb_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = gamble ~ sex * income, data = teengamb)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -52.025 -15.479  -3.559  14.022  48.625 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)      6.8743     9.2446   0.744   0.4612  
## sexMale          1.8427    11.1946   0.165   0.8700  
## income          -0.5489     1.9024  -0.289   0.7743  
## sexMale:income   5.4050     2.1435   2.522   0.0155 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 20.97 on 43 degrees of freedom
## Multiple R-squared:  0.5105, Adjusted R-squared:  0.4764 
## F-statistic: 14.95 on 3 and 43 DF,  p-value: 8.279e-07</code></pre>
<pre class="r"><code>confint(gamb_model)</code></pre>
<pre><code>##                     2.5 %    97.5 %
## (Intercept)    -11.769152 25.517839
## sexMale        -20.733425 24.418773
## income          -4.385455  3.287728
## sexMale:income   1.082260  9.727751</code></pre>
</div>
<div id="valora-si-las-asunciones-del-modelo-se-cumplen"
class="section level3">
<h3>3) Valora si las asunciones del modelo se cumplen</h3>
<pre class="r"><code># Interpretar las 4 gráficas siguientes para decidir si las asunciones del modelo
# se cumplen
plot(gamb_model, ask = FALSE)</code></pre>
<p><img src="entrega_files/figure-html/unnamed-chunk-4-1.png" width="672" /><img src="entrega_files/figure-html/unnamed-chunk-4-2.png" width="672" /><img src="entrega_files/figure-html/unnamed-chunk-4-3.png" width="672" /><img src="entrega_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<p><strong>¿Es el modelo correcto?:</strong></p>
</div>
<div id="interpreta-los-coeficientes-y-escribe-tus-conclusiones."
class="section level3">
<h3>4) Interpreta los coeficientes y escribe tus conclusiones.</h3>
<p>De la tabla de p-valores, podemos concluir que para las mujeres:
<span class="math display">\[gambling = 6.87 - 0.5489 * income\]</span>
Mientras que para hombres: <span class="math display">\[gambling
=  8.72  + 4.8561 * income\]</span>. Fíjate que el coeficiente -0.5489
no es significativo, mientras que el salto en las pendientes entre
mujeres y hombres es de 5.4050 y sí es significativo.</p>
<p><strong>¿Cuáles de las siguientes conclusiones son correctas? (puede
haber varias)</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Los hombres y mujeres adolescentes apuestan de la misma forma.</li>
<li>No evidencia suficiente de que las mujeres apuesten de forma
diferente según sus ingresos.</li>
<li>Para los hombres: a mayor nivel de ingresos, mayor cantidad
apostada.</li>
<li>La diferencia entre las pendientes de hombres y mujeres no es
significativa.</li>
</ol>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
